# Generated by Django 4.2.16 on 2024-09-27 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='description')),
                ('starts_at', models.DateTimeField(verbose_name='starts_at')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('tickets_left', models.IntegerField(default=0, verbose_name='tickets_left')),
            ],
            options={
                'verbose_name': 'Concert',
                'verbose_name_plural': 'Concerts',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ConcertCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'concert category',
                'verbose_name_plural': 'concert categories',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_full_name', models.CharField(max_length=64, verbose_name='customer_full_name')),
                ('payment_method', models.CharField(choices=[('CC', 'Credit card'), ('DC', 'Debit card'), ('ET', 'Ethereum'), ('BC', 'Bitcoin')], default='CC', max_length=2, verbose_name='payment_method')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='paid_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.concert', verbose_name='consert')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.AddField(
            model_name='concert',
            name='categories',
            field=models.ManyToManyField(to='mysite.concertcategory', verbose_name='categories'),
        ),
    ]
